# Generated by Django 4.1 on 2022-08-24 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=100, verbose_name='Марка')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('broken', models.BooleanField(default=False, verbose_name='Битая')),
                ('power', models.IntegerField(verbose_name='Мощность')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Cars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Машина',
                'ordering': ['created'],
            },
        ),
    ]
